import { WebviewAPI } from './WebviewAPI';
import { DappAPI } from './DappAPI';
import { PartnerAPI } from './PartnerAPI';
import { ABCIDAPI } from './ABCIDAPI';
import { PrivateAPI } from './PrivateAPI';
import { BTCAPI } from './BTCAPI';
import { BCHAPI } from './BCHAPI';
import { BSVAPI } from './BSVAPI';
import { LTCAPI } from './LTCAPI';
import { DASHAPI } from './DASHAPI';
import { ETHAPI } from './ETHAPI';
import { ETCAPI } from './ETCAPI';
import { EOSAPI } from './EOSAPI';
import { BrowserAPI } from './BrowserAPI';
export { WebviewAPI, DappAPI, PartnerAPI, ABCIDAPI, PrivateAPI, BTCAPI, BCHAPI, BSVAPI, LTCAPI, DASHAPI, ETHAPI, ETCAPI, EOSAPI, BrowserAPI, };
declare const _default: {
    webview: typeof WebviewAPI;
    dapp: typeof DappAPI;
    partner: typeof PartnerAPI;
    abcid: typeof ABCIDAPI;
    private: typeof PrivateAPI;
    btc: typeof BTCAPI;
    bch: typeof BCHAPI;
    bsv: typeof BSVAPI;
    ltc: typeof LTCAPI;
    dash: typeof DASHAPI;
    eth: typeof ETHAPI;
    etc: typeof ETCAPI;
    eos: typeof EOSAPI;
    browser: typeof BrowserAPI;
};
export default _default;
